# Generated by Django 3.0.6 on 2020-08-18 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='questions_answered',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='questions_asked',
            field=models.IntegerField(default=0),
        ),
    ]
