# Generated by Django 3.0.8 on 2020-08-19 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20200818_1220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='questions_answered',
        ),
        migrations.RemoveField(
            model_name='question',
            name='questions_asked',
        ),
    ]
